using System;
using Sofa3.Domain.Core;

namespace Sofa3.Domain.SprintReport;

public sealed class DefaultReportLayoutStrategy : ReportLayoutStrategy
{
    public string Name => "Default";

    public string Format(Sprint sprint)
    {
        ArgumentNullException.ThrowIfNull(sprint);
        return $"Sprint report for {sprint.Name}";
    }

    public void ApplyTo(SprintReport report)
    {
        ArgumentNullException.ThrowIfNull(report);
        report.LayoutName = Name;
        report.HeaderText = "Sprint report";
        report.FooterText = "Generated by Sofa3";
    }
}

