using Sofa3.Domain.Core;
using Sofa3.Domain.SprintReport;
using SprintReportModel = Sofa3.Domain.SprintReport.SprintReport;

namespace TestProject1.SprintReport.Test;

public class DefaultReportLayoutStrategyTests
{
    [Test]
    public void Name_is_Default()
    {
        var strategy = new DefaultReportLayoutStrategy();

        Assert.That(strategy.Name, Is.EqualTo("Default"));
    }

    [Test]
    public void Format_returns_expected_text()
    {
        var strategy = new DefaultReportLayoutStrategy();
        var sprint = new Sprint(Guid.NewGuid(), "Sprint 1");

        var formatted = strategy.Format(sprint);

        Assert.That(formatted, Is.EqualTo("Sprint report for Sprint 1"));
    }

    [Test]
    public void ApplyTo_sets_layout_header_and_footer()
    {
        var strategy = new DefaultReportLayoutStrategy();
        var report = new SprintReportModel { Version = "1.0.0" };

        strategy.ApplyTo(report);

        Assert.Multiple(() =>
        {
            Assert.That(report.LayoutName, Is.EqualTo("Default"));
            Assert.That(report.HeaderText, Is.EqualTo("Sprint report"));
            Assert.That(report.FooterText, Is.EqualTo("Generated by Sofa3"));
        });
    }

    [Test]
    public void Format_vereist_een_geldige_sprint()
    {
        var strategy = new DefaultReportLayoutStrategy();

        var ex = Assert.Throws<ArgumentNullException>(() => strategy.Format(null!));

        Assert.That(ex!.ParamName, Is.EqualTo("sprint"));
    }

    [Test]
    public void ApplyTo_vereist_een_geldige_report()
    {
        var strategy = new DefaultReportLayoutStrategy();

        var ex = Assert.Throws<ArgumentNullException>(() => strategy.ApplyTo(null!));

        Assert.That(ex!.ParamName, Is.EqualTo("report"));
    }
}

